# (3주차) 3월21일 

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

### 강의영상 

> youtube: 

### imports 

In [4]:
import tensorflow as tf
import numpy as np

In [5]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### 지난강의 보충 

`-` 예제: (2,3,4), (2,3,4), (2,3,4)

(예시1) (2,3,4), (2,3,4), (2,3,4) $\to$ (6,3,4)

In [13]:
a=tf.reshape(tf.constant(range(2*3*4)),(2,3,4))
b=-a
c=2*a

In [14]:
a,b,c

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]],
 
        [[-12, -13, -14, -15],
         [-16, -17, -18, -19],
         [-20, -21, -22, -23]]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 0,  2,  4,  6],
         [ 8, 10, 12, 14],
         [16, 18, 20, 22]],
 
        [[24, 26, 28, 30],
         [32, 34, 36, 38],
         [40, 42, 44, 46]]], dtype=int32)>)

In [10]:
tf.concat([a,b,c],axis=0)

<tf.Tensor: shape=(6, 3, 4), dtype=int32, numpy=
array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]],

       [[  0,   2,   4,   6],
        [  8,  10,  12,  14],
        [ 16,  18,  20,  22]],

       [[ 24,  26,  28,  30],
        [ 32,  34,  36,  38],
        [ 40,  42,  44,  46]]], dtype=int32)>

(예시2) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,9,4)

In [11]:
tf.concat([a,b,c],axis=1)

<tf.Tensor: shape=(2, 9, 4), dtype=int32, numpy=
array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11],
        [  0,   2,   4,   6],
        [  8,  10,  12,  14],
        [ 16,  18,  20,  22]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23],
        [ 24,  26,  28,  30],
        [ 32,  34,  36,  38],
        [ 40,  42,  44,  46]]], dtype=int32)>

(예시3) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,12)

In [12]:
tf.concat([a,b,c],axis=2)

<tf.Tensor: shape=(2, 3, 12), dtype=int32, numpy=
array([[[  0,   1,   2,   3,   0,  -1,  -2,  -3,   0,   2,   4,   6],
        [  4,   5,   6,   7,  -4,  -5,  -6,  -7,   8,  10,  12,  14],
        [  8,   9,  10,  11,  -8,  -9, -10, -11,  16,  18,  20,  22]],

       [[ 12,  13,  14,  15, -12, -13, -14, -15,  24,  26,  28,  30],
        [ 16,  17,  18,  19, -16, -17, -18, -19,  32,  34,  36,  38],
        [ 20,  21,  22,  23, -20, -21, -22, -23,  40,  42,  44,  46]]],
      dtype=int32)>

(예시4) (2,3,4), (2,3,4), (2,3,4) $\to$ (3,2,3,4) # axis=0 

In [17]:
tf.stack([a,b,c],axis=0)

<tf.Tensor: shape=(3, 2, 3, 4), dtype=int32, numpy=
array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],

        [[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]]],


       [[[  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]],

        [[-12, -13, -14, -15],
         [-16, -17, -18, -19],
         [-20, -21, -22, -23]]],


       [[[  0,   2,   4,   6],
         [  8,  10,  12,  14],
         [ 16,  18,  20,  22]],

        [[ 24,  26,  28,  30],
         [ 32,  34,  36,  38],
         [ 40,  42,  44,  46]]]], dtype=int32)>

(예시5) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,3,4) # axis=1

In [18]:
tf.stack([a,b,c],axis=1)

<tf.Tensor: shape=(2, 3, 3, 4), dtype=int32, numpy=
array([[[[  0,   1,   2,   3],
         [  4,   5,   6,   7],
         [  8,   9,  10,  11]],

        [[  0,  -1,  -2,  -3],
         [ -4,  -5,  -6,  -7],
         [ -8,  -9, -10, -11]],

        [[  0,   2,   4,   6],
         [  8,  10,  12,  14],
         [ 16,  18,  20,  22]]],


       [[[ 12,  13,  14,  15],
         [ 16,  17,  18,  19],
         [ 20,  21,  22,  23]],

        [[-12, -13, -14, -15],
         [-16, -17, -18, -19],
         [-20, -21, -22, -23]],

        [[ 24,  26,  28,  30],
         [ 32,  34,  36,  38],
         [ 40,  42,  44,  46]]]], dtype=int32)>

(예시6) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,3,4) # axis=2

In [21]:
tf.stack([a,b,c],axis=2)

<tf.Tensor: shape=(2, 3, 3, 4), dtype=int32, numpy=
array([[[[  0,   1,   2,   3],
         [  0,  -1,  -2,  -3],
         [  0,   2,   4,   6]],

        [[  4,   5,   6,   7],
         [ -4,  -5,  -6,  -7],
         [  8,  10,  12,  14]],

        [[  8,   9,  10,  11],
         [ -8,  -9, -10, -11],
         [ 16,  18,  20,  22]]],


       [[[ 12,  13,  14,  15],
         [-12, -13, -14, -15],
         [ 24,  26,  28,  30]],

        [[ 16,  17,  18,  19],
         [-16, -17, -18, -19],
         [ 32,  34,  36,  38]],

        [[ 20,  21,  22,  23],
         [-20, -21, -22, -23],
         [ 40,  42,  44,  46]]]], dtype=int32)>

(예시7) (2,3,4), (2,3,4), (2,3,4) $\to$ (2,3,4,3) # axis=3

In [22]:
tf.stack([a,b,c],axis=3)

<tf.Tensor: shape=(2, 3, 4, 3), dtype=int32, numpy=
array([[[[  0,   0,   0],
         [  1,  -1,   2],
         [  2,  -2,   4],
         [  3,  -3,   6]],

        [[  4,  -4,   8],
         [  5,  -5,  10],
         [  6,  -6,  12],
         [  7,  -7,  14]],

        [[  8,  -8,  16],
         [  9,  -9,  18],
         [ 10, -10,  20],
         [ 11, -11,  22]]],


       [[[ 12, -12,  24],
         [ 13, -13,  26],
         [ 14, -14,  28],
         [ 15, -15,  30]],

        [[ 16, -16,  32],
         [ 17, -17,  34],
         [ 18, -18,  36],
         [ 19, -19,  38]],

        [[ 20, -20,  40],
         [ 21, -21,  42],
         [ 22, -22,  44],
         [ 23, -23,  46]]]], dtype=int32)>

`-` 예제: (2,3,4) (4,3,4) $\to$ (6,3,4) 

In [23]:
a=tf.reshape(tf.constant(range(2*3*4)),(2,3,4))
b=tf.reshape(-tf.constant(range(4*3*4)),(4,3,4)) 

In [29]:
tf.concat([a,b],axis=0)

<tf.Tensor: shape=(6, 3, 4), dtype=int32, numpy=
array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[  0,  -1,  -2,  -3],
        [ -4,  -5,  -6,  -7],
        [ -8,  -9, -10, -11]],

       [[-12, -13, -14, -15],
        [-16, -17, -18, -19],
        [-20, -21, -22, -23]],

       [[-24, -25, -26, -27],
        [-28, -29, -30, -31],
        [-32, -33, -34, -35]],

       [[-36, -37, -38, -39],
        [-40, -41, -42, -43],
        [-44, -45, -46, -47]]], dtype=int32)>

In [30]:
tf.concat([a,b],axis=1) # 에러

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [2,3,4] vs. shape[1] = [4,3,4] [Op:ConcatV2] name: concat

In [31]:
tf.concat([a,b],axis=2) # 에러

InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [2,3,4] vs. shape[1] = [4,3,4] [Op:ConcatV2] name: concat

`-` tf.random