# (2주차) 3월14일, draft

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tf.config.experimental.list_physical_devices('GPU')

2022-03-14 15:21:15.520866: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### tf.constant 

#### 예비학습: 중첩리스트 

`-` (2,) vector

In [3]:
lst = [1,2] 

In [4]:
lst

[1, 2]

In [5]:
lst[0] # 

1

In [6]:
lst[1]

2

`-` (2,2) matrix  

In [7]:
lst = [[1,2],[3,4]]

In [8]:
lst[0][0]

1

In [9]:
lst[1][1]

4

```
1 2 
3 4 
```

In [10]:
print(lst[0][0]) # (1,1) 
print(lst[0][1]) # (1,2)
print(lst[1][0]) # (2,1) 
print(lst[1][1]) # (2,2) 

1
2
3
4


매트릭스는 아니지만 매트릭스 같음 

`-` (4,1) matrix 

In [11]:
lst = [[1,2],[3,4],[5,6],[7,8]]
lst # (4,2) 

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [12]:
lst = [[1],[3],[5],[7]]
lst # (4,1) matrix = 길이가 4인 col-vector 

[[1], [3], [5], [7]]

`-` (1,4) matrix 

In [13]:
lst = [[1,2,3,4],[5,6,7,8]]
lst # (2,4) matrix  

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [14]:
lst = [[1,2,3,4]]
lst # (1,4) matrix = 길이가 4인 row-vector  

[[1, 2, 3, 4]]

`-` 3차원 

In [15]:
lst = [[[1,2],[3,4]], [[5,6],[7,8]]]
lst 

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [16]:
print(lst[0][0][0])
print(lst[0][0][1])
print(lst[0][1][0])
print(lst[0][1][1])
print(lst[1][0][0])
print(lst[1][0][1])
print(lst[1][1][0])
print(lst[1][1][1])

1
2
3
4
5
6
7
8


#### 선언

`-` 스칼라 

In [17]:
_scalar =tf.constant(1)
_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

`-` 벡터

In [18]:
_vector=tf.constant([1,2,3])
_vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [19]:
_vector[-2]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

`-` 매트릭스 

In [20]:
_matrix=tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [21]:
_matrix[0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#### 타입

In [22]:
type(_scalar)

tensorflow.python.framework.ops.EagerTensor

#### 인덱싱 

In [23]:
_matrix=tf.constant([[1,2,3],[3,4,5]])
_matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [24]:
_matrix[0,:] 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [25]:
_matrix[:,0] 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [26]:
_matrix[:,-1] 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

#### tf.constant는 불편하다. 

`-` 불편한점 
1. dtype이 모든 원소가 똑같아야한다. (그럴수 있음) 
2. 값을 바꿀 수가 없다. 
3. dtype이 다르면 연산이 불가능함. 

`-` 값을 바꿀 수 없다. 

In [27]:
_matrix=tf.constant([[1,2,3],[3,4,5]])
_matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [28]:
_matrix[0,0]=22

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

`-` dtype이 다르면 연산이 불가능함 

In [29]:
tf.constant([1.1,2])+tf.constant([3,4])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [ ]:
tf.constant([1.1,2])+tf.constant([3.0,4.0])

`-` 같은 float형이라도 불가능할 때가 있음 

In [30]:
tf.constant([1.1,2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.1, 2. ], dtype=float32)>

In [31]:
tf.constant([3.0,4.0],dtype=tf.float64)

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([3., 4.])>

In [32]:
tf.constant([1.1,2])+tf.constant([3.0,4.0],dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

#### tf.constant $\to$ 넘파이 

In [33]:
_vector = tf.constant([1,2,3,4])
_vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [34]:
np.array(_vector) # 방법1

array([1, 2, 3, 4], dtype=int32)

In [35]:
_vector.numpy()

array([1, 2, 3, 4], dtype=int32)

#### 연산

`-` 더하기 

In [36]:
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
a+b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [37]:
tf.add(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

`-` 곱하기 

In [38]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[4,5],[6,7]])
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 10],
       [18, 28]], dtype=int32)>

In [39]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [6, 7]], dtype=int32)>)

In [40]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 10],
       [18, 28]], dtype=int32)>

`-` 행렬곱 

In [41]:
a=tf.constant([[1,0],[0,1]]) 
b= tf.constant([[1],[22]]) 

In [42]:
a @ b # (2,2) matrix @ (2,1) matrix 

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 1],
       [22]], dtype=int32)>

In [43]:
b @ a # (2,1) matrix @ (2,2) matrix

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,1], In[1]: [2,2] [Op:MatMul]

In [44]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 1],
       [22]], dtype=int32)>

`-` 역행렬

In [45]:
a= tf.constant([[1,0],[0,2]]) 
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 2]], dtype=int32)>

In [46]:
tf.linalg.inv(a)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse]

In [47]:
a= tf.constant([[1.0,2.0],[3.0,4.0]]) 
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [48]:
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2. ,  1. ],
       [ 1.5, -0.5]], dtype=float32)>

In [49]:
a @ tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

`-` `tf.linalg. + tab`을 누르면 쓸만한게 조금 나온다. 

In [50]:
a=tf.constant([[1.0,2.0],[3.0,4.0]])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [51]:
tf.linalg.det(a)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [52]:
tf.linalg.trace(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

`-` 단순한 집계함수들 

In [55]:
a=tf.constant([[1,2,3],[4,5,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [56]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [59]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

`-` 행렬곱 고급 

In [62]:
_I=tf.constant([[1.0,0.0],[0.0,1.0]])
_I

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [71]:
_x = tf.constant([22.0,33.0])
_x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([22., 33.], dtype=float32)>

(상황1)

In [72]:
_I @ _x

InvalidArgumentError: In[0] and In[1] has different ndims: [2,2] vs. [2] [Op:MatMul]

In [73]:
_x @ _I 

InvalidArgumentError: In[0] and In[1] has different ndims: [2] vs. [2,2] [Op:MatMul]

(상황2)

In [75]:
_x = tf.constant([[1.0],[2.0]])
_x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [76]:
_I @ _x 

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [77]:
_x @ _I

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,1], In[1]: [2,2] [Op:MatMul]

(상황3)

In [78]:
_x = tf.constant([[1.0,2.0]])
_x

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>

In [79]:
_I @ _x 

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,2], In[1]: [1,2] [Op:MatMul]

In [80]:
_x @ _I 

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>

(넘파이는 다르다..)

In [88]:
np.array([22,33]) @ np.diag([1,1]) 

array([22, 33])

In [89]:
np.array([[22],[33]]) @ np.diag([1,1])

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

#### 형태변환

`-` tf.reshape 기본 

In [92]:
a=tf.constant([1,2,3,4])
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [93]:
tf.reshape(a,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [94]:
tf.reshape(a,(4,1))

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [95]:
tf.reshape(a,(1,4))

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

`-` tf.reshape 응용 

In [99]:
a= tf.constant([0,1,2,3,4,5,6,7,8,9,10,11]) # length 12 vector
a

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [100]:
tf.reshape(a,(4,3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>

In [101]:
tf.reshape(a,(2,2,3))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)>

In [102]:
tf.reshape(a,(3,-1))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [103]:
tf.reshape(a,(2,2,-1))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)>

In [105]:
b=tf.reshape(a,(2,2,-1))
b

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)>

In [107]:
tf.reshape(b,-1)

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

#### 선언고급 

`-` 대각행렬선언 

In [110]:
tf.constant(np.diag([1,2,3]))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])>

`-` 1만 포함한 텐서를 만들고 싶음 

In [113]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [116]:
tf.reshape(tf.constant([1]*12),(3,4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

#### tf.concat 

#### tf.stack 

#### tf.einsum

### tnp

#### tnp 사용방법 (불만해결방법)

#### 선언, 선언고급

#### 타입

#### tf.contant로 만들어도 마치 넘파이인듯 쓰는 기능들

#### 그렇지만 np.array는 아님 

### tf.Variable

#### 선언 

#### 타입

#### 인덱싱 

#### tf.Variable $\to$ 넘파이 

#### tf.Variable 도 불편하다. 

#### 연산 

#### 형태변환 

#### 선언고급 

#### tf.concat 

#### tf.stack

#### 심지어 tf.Variable()로 만들어진 오브젝트는 tnp의 효과(은총)도 받지 못함