# (2주차) 3월14일, draft

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### tf.constant 

#### 예비학습: 중첩리스트 

`-` (2,) vector

In [4]:
lst = [1,2] 

In [5]:
lst

[1, 2]

In [7]:
lst[0] # 

1

In [8]:
lst[1]

2

`-` (2,2) matrix  

In [18]:
lst = [[1,2],[3,4]]

In [20]:
lst[0][0]

1

In [21]:
lst[1][1]

4

```
1 2 
3 4 
```

In [25]:
print(lst[0][0]) # (1,1) 
print(lst[0][1]) # (1,2)
print(lst[1][0]) # (2,1) 
print(lst[1][1]) # (2,2) 

1
2
3
4


매트릭스는 아니지만 매트릭스 같음 

`-` (4,1) matrix 

In [27]:
lst = [[1,2],[3,4],[5,6],[7,8]]
lst # (4,2) 

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [36]:
lst = [[1],[3],[5],[7]]
lst # (4,1) matrix = 길이가 4인 col-vector 

[[1], [3], [5], [7]]

`-` (1,4) matrix 

In [34]:
lst = [[1,2,3,4],[5,6,7,8]]
lst # (2,4) matrix  

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [35]:
lst = [[1,2,3,4]]
lst # (1,4) matrix = 길이가 4인 row-vector  

[[1, 2, 3, 4]]

`-` 3차원 

In [38]:
lst = [[[1,2],[3,4]], [[5,6],[7,8]]]
lst 

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [40]:
print(lst[0][0][0])
print(lst[0][0][1])
print(lst[0][1][0])
print(lst[0][1][1])
print(lst[1][0][0])
print(lst[1][0][1])
print(lst[1][1][0])
print(lst[1][1][1])

1
2
3
4
5
6
7
8


#### 선언

`-` 스칼라 

In [47]:
_scalar =tf.constant(1)
_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

`-` 벡터

In [49]:
_vector=tf.constant([1,2,3])
_vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [52]:
_vector[-2]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

`-` 매트릭스 

In [54]:
_matrix=tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [61]:
_matrix[0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#### 타입

In [62]:
type(_scalar)

tensorflow.python.framework.ops.EagerTensor

#### 인덱싱 

In [64]:
_matrix=tf.constant([[1,2,3],[3,4,5]])
_matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [72]:
_matrix[0,:] 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [73]:
_matrix[:,0] 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [74]:
_matrix[:,-1] 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

#### tf.constant는 불편하다. 

`-` 불편한점 
1. dtype이 모든 원소가 똑같아야한다. (그럴수 있음) 
2. 값을 바꿀 수가 없다. 
3. dtype이 다르면 연산이 불가능함. 

`-` 값을 바꿀 수 없다. 

In [86]:
_matrix=tf.constant([[1,2,3],[3,4,5]])
_matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [87]:
_matrix[0,0]=22

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

`-` dtype이 다르면 연산이 불가능함 

In [84]:
tf.constant([1.1,2])+tf.constant([3,4])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [85]:
tf.constant([1.1,2])+tf.constant([3.0,4.0])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.1, 6. ], dtype=float32)>

#### tf.constant $\to$ 넘파이 

#### 연산

#### 형태변환

#### 선언고급 

#### tf.concat 

#### tf.stack 

#### tf.einsum

### tnp

#### tnp 사용방법 (불만해결방법)

#### 선언, 선언고급

#### 타입

#### tf.contant로 만들어도 마치 넘파이인듯 쓰는 기능들

#### 그렇지만 np.array는 아님 

### tf.Variable

#### 선언 

#### 타입

#### 인덱싱 

#### tf.Variable $\to$ 넘파이 

#### tf.Variable 도 불편하다. 

#### 연산 

#### 형태변환 

#### 선언고급 

#### tf.concat 

#### tf.stack

#### 심지어 tf.Variable()로 만들어진 오브젝트는 tnp의 효과(은총)도 받지 못함