# (3주차) 3월16일 - draft

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

### 강의영상

> youtube: 

### import 

In [3]:
import tensorflow as tf
import numpy as np

In [4]:
tf.config.experimental.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### tf.constant 

#### 선언고급 

`-` 대각행렬선언 

In [5]:
tf.constant(np.diag([1,2,3]))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])>

`-` 1만 포함한 텐서를 만들고 싶음 

In [6]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [7]:
tf.reshape(tf.constant([1]*12),(3,4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

#### tf.concat 

#### tf.stack 

### tnp

(불만1) reshape

(불만2) transpose 

(불만3) 암묵적형변환

(불만4) 집계함수

(불만5) random.randn.. 

#### tnp 사용방법 (불만해결방법)

#### 선언고급

#### 타입

#### tf.contant로 만들어도 마치 넘파이인듯 쓰는 기능들

#### 그렇지만 np.array는 아님 