# (2주차) 3월14일

- toc:true
- branch: master
- badges: true
- comments: true
- author: 최규빈

### 강의영상 

> https://youtube.com/playlist?list=PLQqh36zP38-ySV9-HcHZ7luZ9lptCPh98

### import 

In [117]:
import tensorflow as tf
import numpy as np

In [196]:
tf.config.experimental.list_physical_devices('GPU') # check GPU 

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

### tf.constant 

#### 예비학습: 중첩리스트 

`-` (2,) vector

In [119]:
lst = [1,2] 

In [120]:
lst

[1, 2]

In [121]:
lst[0] # 

1

In [122]:
lst[1]

2

`-` (2,2) matrix  

In [123]:
lst = [[1,2],[3,4]]

In [124]:
lst[0][0]

1

In [125]:
lst[1][1]

4

이것은 아래와 같은 매트릭스처럼 생각할 수 있음 

```
1 2 
3 4 
```

In [126]:
print(lst[0][0]) # (1,1) 
print(lst[0][1]) # (1,2)
print(lst[1][0]) # (2,1) 
print(lst[1][1]) # (2,2) 

1
2
3
4


매트릭스는 아니지만 매트릭스 같음 

`-` (4,1) matrix 

In [11]:
lst = [[1,2],[3,4],[5,6],[7,8]]
lst # (4,2) 

[[1, 2], [3, 4], [5, 6], [7, 8]]

In [12]:
lst = [[1],[3],[5],[7]]
lst # (4,1) matrix = 길이가 4인 col-vector 

[[1], [3], [5], [7]]

`-` (1,4) matrix 

In [13]:
lst = [[1,2,3,4],[5,6,7,8]]
lst # (2,4) matrix  

[[1, 2, 3, 4], [5, 6, 7, 8]]

In [14]:
lst = [[1,2,3,4]]
lst # (1,4) matrix = 길이가 4인 row-vector  

[[1, 2, 3, 4]]

`-` 3차원 

In [15]:
lst = [[[1,2],[3,4]], [[5,6],[7,8]]]
lst 

[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

In [16]:
print(lst[0][0][0])
print(lst[0][0][1])
print(lst[0][1][0])
print(lst[0][1][1])
print(lst[1][0][0])
print(lst[1][0][1])
print(lst[1][1][0])
print(lst[1][1][1])

1
2
3
4
5
6
7
8


#### 선언

`-` 스칼라 

In [127]:
_scalar =tf.constant(1)
_scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

`-` 벡터

In [128]:
_vector=tf.constant([1,2,3])
_vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [129]:
_vector[-2]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

`-` 매트릭스 

In [130]:
_matrix=tf.constant([[1,2],[3,4]])
_matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [131]:
_matrix[0,1]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#### 타입

In [132]:
type(_scalar)

tensorflow.python.framework.ops.EagerTensor

#### 인덱싱 

In [133]:
_matrix=tf.constant([[1,2,3],[3,4,5]])
_matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [134]:
_matrix[0,:] 

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [135]:
_matrix[:,0] 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [136]:
_matrix[:,-1] 

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

#### tf.constant는 불편하다. 

`-` 불편한점 
1. dtype이 모든 원소가 똑같아야한다. (그럴수 있음) 
2. 값을 바꿀 수가 없다. 
3. dtype이 다르면 연산이 불가능함. 

`-` 값을 바꿀 수 없다. 

In [137]:
_matrix=tf.constant([[1,2,3],[3,4,5]])
_matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5]], dtype=int32)>

In [138]:
_matrix[0,0]=22

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

`-` dtype이 다르면 연산이 불가능함 

In [139]:
tf.constant([1.1,2])+tf.constant([3,4])

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [140]:
tf.constant([1.1,2])+tf.constant([3.0,4.0])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.1, 6. ], dtype=float32)>

`-` 같은 float형이라도 불가능할 때가 있음 

In [141]:
tf.constant([1.1,2])

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.1, 2. ], dtype=float32)>

In [142]:
tf.constant([3.0,4.0],dtype=tf.float64)

<tf.Tensor: shape=(2,), dtype=float64, numpy=array([3., 4.])>

In [143]:
tf.constant([1.1,2])+tf.constant([3.0,4.0],dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a double tensor [Op:AddV2]

#### tf.constant $\to$ 넘파이 

In [144]:
_vector = tf.constant([1,2,3,4])
_vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [145]:
np.array(_vector) # 방법1

array([1, 2, 3, 4], dtype=int32)

In [146]:
_vector.numpy()

array([1, 2, 3, 4], dtype=int32)

#### 연산

`-` 더하기 

In [147]:
a=tf.constant([1,2,3])
b=tf.constant([4,5,6])
a+b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [148]:
tf.add(a,b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

`-` 곱하기 

In [149]:
a=tf.constant([[1,2],[3,4]])
b=tf.constant([[4,5],[6,7]])
a*b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 10],
       [18, 28]], dtype=int32)>

In [150]:
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[4, 5],
        [6, 7]], dtype=int32)>)

In [151]:
tf.multiply(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 4, 10],
       [18, 28]], dtype=int32)>

`-` 행렬곱 

In [152]:
a=tf.constant([[1,0],[0,1]]) 
b= tf.constant([[1],[22]]) 

In [153]:
a @ b # (2,2) matrix @ (2,1) matrix 

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 1],
       [22]], dtype=int32)>

In [154]:
b @ a # (2,1) matrix @ (2,2) matrix

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,1], In[1]: [2,2] [Op:MatMul]

In [155]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[ 1],
       [22]], dtype=int32)>

`-` 역행렬

In [156]:
a= tf.constant([[1,0],[0,2]]) 
a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 2]], dtype=int32)>

In [157]:
tf.linalg.inv(a)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixInverse}}; Op<name=MatrixInverse; signature=input:T -> output:T; attr=adjoint:bool,default=false; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]> [Op:MatrixInverse]

In [158]:
a= tf.constant([[1.0,2.0],[3.0,4.0]]) 
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [159]:
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2. ,  1. ],
       [ 1.5, -0.5]], dtype=float32)>

In [160]:
a @ tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

`-` `tf.linalg. + tab`을 누르면 쓸만한게 조금 나온다. 

In [161]:
a=tf.constant([[1.0,2.0],[3.0,4.0]])
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [162]:
tf.linalg.det(a)

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

In [163]:
tf.linalg.trace(a)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

`-` 단순한 집계함수들 

In [164]:
a=tf.constant([[1,2,3],[4,5,6]])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [165]:
tf.reduce_sum(a)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [166]:
tf.reduce_max(a)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

`-` 행렬곱 고급 

In [167]:
_I=tf.constant([[1.0,0.0],[0.0,1.0]])
_I

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [168]:
_x = tf.constant([22.0,33.0])
_x

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([22., 33.], dtype=float32)>

(상황1)

In [169]:
_I @ _x

InvalidArgumentError: In[0] and In[1] has different ndims: [2,2] vs. [2] [Op:MatMul]

In [170]:
_x @ _I 

InvalidArgumentError: In[0] and In[1] has different ndims: [2] vs. [2,2] [Op:MatMul]

(상황2)

In [171]:
_x = tf.constant([[1.0],[2.0]])
_x

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [172]:
_I @ _x 

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [2.]], dtype=float32)>

In [173]:
_x @ _I

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,1], In[1]: [2,2] [Op:MatMul]

(상황3)

In [174]:
_x = tf.constant([[1.0,2.0]])
_x

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>

In [175]:
_I @ _x 

InvalidArgumentError: Matrix size-incompatible: In[0]: [2,2], In[1]: [1,2] [Op:MatMul]

In [176]:
_x @ _I 

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 2.]], dtype=float32)>

(넘파이는 다르다..)

In [180]:
np.array([22,33]) @ np.diag([1,1]) # (2,) @ (2,2) ==> (2,)를 (1,2)벡터로 해석해줘서 곱하기 수행, 수행결과는 다시 (2,)로 저장

array([22, 33])

In [181]:
np.array([[22],[33]]) @ np.diag([1,1]) # (2,1) @ (2,2)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

#### 형태변환

`-` tf.reshape 기본 

In [182]:
a=tf.constant([1,2,3,4])
a

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [183]:
tf.reshape(a,(2,2))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [184]:
tf.reshape(a,(4,1))

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4]], dtype=int32)>

In [185]:
tf.reshape(a,(1,4))

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>

`-` tf.reshape 응용 

In [186]:
a= tf.constant([0,1,2,3,4,5,6,7,8,9,10,11]) # length 12 vector
a

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [187]:
tf.reshape(a,(4,3))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>

In [188]:
tf.reshape(a,(2,2,3))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)>

In [189]:
tf.reshape(a,(3,-1))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [190]:
tf.reshape(a,(2,2,-1))

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)>

In [191]:
b=tf.reshape(a,(2,2,-1))
b

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)>

In [192]:
tf.reshape(b,-1)

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

#### 선언고급 

`-` 대각행렬선언 

In [193]:
tf.constant(np.diag([1,2,3]))

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])>

`-` 1만 포함한 텐서를 만들고 싶음 

In [194]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [195]:
tf.reshape(tf.constant([1]*12),(3,4))

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>